package elemental3;

import javax.annotation.Generated;
import javax.annotation.Nonnull;
import jsinterop.annotations.JsPackage;
import jsinterop.annotations.JsProperty;
import jsinterop.annotations.JsType;

/**
 * The DOM CompositionEvent represents events that occur due to the user indirectly entering text.
 *
 * @see <a href="https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent">CompositionEvent - MDN</a>
 */
@Generated("org.realityforge.webtack")
@JsType(
    isNative = true,
    namespace = JsPackage.GLOBAL,
    name = "CompositionEvent"
)
public class CompositionEvent extends UIEvent {
  public CompositionEvent(@Nonnull final String type,
      @Nonnull final CompositionEventInit eventInitDict) {
    super( null );
  }

  public CompositionEvent(@Nonnull final String type) {
    super( null );
  }

  /**
   * The data read-only property of the CompositionEvent interface returns the characters generated by the input method that raised the event; its exact nature varies depending on the type of event that generated the CompositionEvent object.
   *
   * @see <a href="https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent/data">CompositionEvent.data - MDN</a>
   */
  @JsProperty(
      name = "data"
  )
  @Nonnull
  public native String data();
}
